# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: alexsayantan
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ragenet

provider:
  name: aws
  runtime: python3.12
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com


plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  signup:
    handler: auth.signup.handler
    events:
      - httpApi:
          path: /signup
          method: post
  signin:
    handler: auth.signin.handler
    events:
      - httpApi:
          path: /signin
          method: post
