# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: alexsayantan
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ragenet

provider:
  name: aws
  runtime: python3.12

package:
  patterns:
    - '!**/__pycache__/**'
    - '!**/*.pyc'
    - '!.venv/**'
    - '!.git/**'
    - '!alembic/**'
    - '!alembic.ini'
    - '!README.md'

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  signup:
    handler: auth.signup.handler
    events:
      - httpApi:
          path: /signup
          method: post
  signin:
    handler: auth.signin.handler
    events:
      - httpApi:
          path: /signin
          method: post
  user-details:
    handler: user.user_details.handler
    events:
      - httpApi:
          path: /user-details
          method: get
      - httpApi:
          path: /user-details
          method: put
  check-username:
    handler: auth.check_username.handler
    events:
      - httpApi:
          path: /check-username
          method: get
